name: Haskell CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10.5", "9.2.2", "9.4.4"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: haskell/actions/setup@968e175ff94d685b6ce0bb39b02447cca8b4a6bb
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - uses: actions/cache@v2
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-repo-dist

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-configure --write-ghc-environment-files=always -j2 -O0
        cabal v2-build --only-dependencies all

    - name: Build & test
      run: |
        cabal v2-build all
        cabal v2-haddock all

    - name: Build example app
      run: |
        cd ./example && cabal v2-build all
